spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yang_cms?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: hello
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  redis:
    host: 127.0.0.1
    port: 6379
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
management:
  endpoints:
    web:
      exposure:
        include: '*'  # 启用所有的监控端点， 默认是全部关闭的
logging:
  level:
    root: info
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
security:
  oauth2:
    client:
      client-id: web_app
      client-secret: hello
      access-token-uri: http://localhost:8888/oauth/token
      user-authorization-uri: http://localhost:8888/oauth/authorize
    resource:
      user-info-uri: http://localhost:8888/api/user/info
file:
  upload-folder: /Users/akafra/Documents/upload
