spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yang_auth?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: hello
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      pool-name: DatebookHikariCP
      connection-test-query: SELECT 1
  redis:
    host: 127.0.0.1
    port: 6379
management:
  endpoints:
    web:
      exposure:
        include: '*'  # 启用所有的监控端点， 默认是全部关闭的
logging:
  level:
    root: debug
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
auth:
  store-type: redis
  web-client-configuration:
    access-token-validity-in-seconds: 1800
yang:
  cache:
    hazelcast:
      backup-count: 1
      management-center:
        enabled: true
        url: http://127.0.0.1:7878