spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yang_auth?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: hello
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      pool-name: DatebookHikariCP
      connection-test-query: SELECT 1
  redis:
    host: 127.0.0.1
    port: 6379
  mail:
    host: smtp.163.com
    port: 25
    username: firm_yang@163.com
    password: jazr932832
management:
  endpoints:
    web:
      exposure:
        include: '*'  # 启用所有的监控端点， 默认是全部关闭的
logging:
  level:
    root: debug
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
yang:
  mail:
    enabled: true
    from: firm_yang@163.com
    base-url: http://127.0.0.11024
  sentry:
    enabled: true
    dsn: https://fb416915df2a4e41bce43aafe5489ca4@sentry.io/1421282

